"""empty message

Revision ID: 70165fff9558
Revises: 7c52d228cb39
Create Date: 2016-09-06 16:52:52.780549

"""

# revision identifiers, used by Alembic.
revision = '70165fff9558'
down_revision = '7c52d228cb39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('log', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_logs')
    ### end Alembic commands ###
