"""empty message

Revision ID: 7c52d228cb39
Revises: None
Create Date: 2016-09-06 15:25:14.434765

"""

# revision identifiers, used by Alembic.
revision = '7c52d228cb39'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('tz_offset', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name', 'phone'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data')
    ### end Alembic commands ###
