# database container
db:
  image: postgres:latest
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
# redis container
redis:  
  image: redis
# rabbitmq container
rabbitmq:  
  image: rabbitmq
  ports:
    - "5672:5672"  # we forward this port because it's useful for debugging 
    - "15672:15672"  # here, we can access rabbitmq management plugin

# container with Flask web server
web:  
  build: .  # build using default Dockerfile
  environment:
    - PORT=8000
    - HOST=0.0.0.0
  command: ./run_web.sh
  volumes:
    - .:/MsgApp  # mount current directory inside container
  ports:
    - "8000:8000"
  # set up links so that web knows about db, rabbit and redis
  links:
    - db:db
    - rabbitmq:rabbit
    - redis:redis
# container with redis worker
worker:  
  build: .
  command: ./run_celery.sh
  volumes:
    - .:/MsgApp
  links:
    - db:db
    - rabbitmq:rabbit
    - redis:redis
